using UnityEngine;

public struct MappedInfo
{
    public const int SizeInBytes = 1 * 3 * sizeof(float) + 1 * 2 * sizeof(float) + 1 * sizeof(float) + 9 * 9 * sizeof(float);

    public Vector3 TransformedPixel;
    public Vector2 ReservoirPixel;
    public float Distance;

    // Can't easily make fixed size array so we do this,
    // just so that the values are initialized with zero
    public float Overlap1;
    public float Overlap2;
    public float Overlap3;
    public float Overlap4;
    public float Overlap5;
    public float Overlap6;
    public float Overlap7;
    public float Overlap8;
    public float Overlap9;
    public float Overlap10;
    public float Overlap11;
    public float Overlap12;
    public float Overlap13;
    public float Overlap14;
    public float Overlap15;
    public float Overlap16;
    public float Overlap17;
    public float Overlap18;
    public float Overlap19;
    public float Overlap20;
    public float Overlap21;
    public float Overlap22;
    public float Overlap23;
    public float Overlap24;
    public float Overlap25;
    public float Overlap26;
    public float Overlap27;
    public float Overlap28;
    public float Overlap29;
    public float Overlap30;
    public float Overlap31;
    public float Overlap32;
    public float Overlap33;
    public float Overlap34;
    public float Overlap35;
    public float Overlap36;
    public float Overlap37;
    public float Overlap38;
    public float Overlap39;
    public float Overlap40;
    public float Overlap41;
    public float Overlap42;
    public float Overlap43;
    public float Overlap44;
    public float Overlap45;
    public float Overlap46;
    public float Overlap47;
    public float Overlap48;
    public float Overlap49;
    public float Overlap50;
    public float Overlap51;
    public float Overlap52;
    public float Overlap53;
    public float Overlap54;
    public float Overlap55;
    public float Overlap56;
    public float Overlap57;
    public float Overlap58;
    public float Overlap59;
    public float Overlap60;
    public float Overlap61;
    public float Overlap62;
    public float Overlap63;
    public float Overlap64;
    public float Overlap65;
    public float Overlap66;
    public float Overlap67;
    public float Overlap68;
    public float Overlap69;
    public float Overlap70;
    public float Overlap71;
    public float Overlap72;
    public float Overlap73;
    public float Overlap74;
    public float Overlap75;
    public float Overlap76;
    public float Overlap77;
    public float Overlap78;
    public float Overlap79;
    public float Overlap80;
    public float Overlap81;
}