#include "../ShaderBase/shader_base.hlsl"

#include "../floating_avg.hlsl"

RWStructuredBuffer<float> ValueSourceSink;
RWStructuredBuffer<float> AvgRingbuffer;
uint StrokeBegin;

#pragma kernel test_floating_avg

[numthreads(32,1,1)]
void test_floating_avg(uint3 id_ : SV_DispatchThreadID)
{
    id__ = id_;
    if (is_relevant_thread(id(), CalculationSize))
    {
        float new_value = ValueSourceSink[0];
        ValueSourceSink[0] = floating_avg(AvgRingbuffer, StrokeBegin, new_value);
    }
}